# Generated by Django 5.0 on 2026-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Hotels', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('hero_h1', models.CharField(help_text='Main headline', max_length=200)),
                ('hero_paragraph_1', models.TextField(help_text='First strong paragraph')),
                ('hero_paragraph_2', models.TextField(help_text='Second strong paragraph')),
                ('hero_paragraph_3', models.TextField(help_text='Third strong paragraph')),
                ('hero_cta_text', models.CharField(default='Request Supply Quote', max_length=100)),
                ('hero_image', models.ImageField(blank=True, help_text='Right side image - hotel kitchen/professional setting', null=True, upload_to='sectors/hero/')),
                ('trust_h2', models.CharField(help_text='Trust section headline', max_length=200)),
                ('trust_paragraph', models.TextField(help_text='Main trust paragraph covering local sourcing, delivery, etc.')),
                ('trust_cta_text', models.CharField(default='Speak to Our Supply Team', max_length=100)),
                ('split_left_h2', models.CharField(help_text='Headline for left split section', max_length=200)),
                ('split_left_content', models.TextField(help_text='Content about seasonal produce, local farms, quality control')),
                ('split_left_cta_text', models.CharField(default='Learn More', max_length=100)),
                ('split_left_image', models.ImageField(blank=True, help_text='Fresh produce crates/hotel kitchen', null=True, upload_to='sectors/split/')),
                ('split_right_h2', models.CharField(help_text='Headline for right split section', max_length=200)),
                ('split_right_content', models.TextField(help_text='Content about time-saving, pre-cut vegetables, bulk supply')),
                ('split_right_cta_text', models.CharField(default='Get Started', max_length=100)),
                ('split_right_image', models.ImageField(blank=True, help_text='Chef preparing food', null=True, upload_to='sectors/split/')),
                ('operations_h2', models.CharField(help_text='Operations headline', max_length=200)),
                ('operations_content', models.TextField(help_text='Content about scheduled delivery, inventory, emergency supply, account managers')),
                ('partner_h2', models.CharField(help_text='Partnership headline', max_length=200)),
                ('partner_content', models.TextField(help_text='Why partner with Terra Foods')),
                ('partner_cta_text', models.CharField(default='Become a Partner', max_length=100)),
                ('partner_image', models.ImageField(blank=True, help_text='Premium produce display', null=True, upload_to='sectors/partner/')),
                ('dark_cta_h2', models.CharField(help_text='Final CTA headline', max_length=200)),
                ('dark_cta_paragraph', models.TextField(help_text='Final compelling paragraph')),
                ('dark_cta_button_text', models.CharField(default='Request Quote', max_length=100)),
                ('dark_cta_image', models.ImageField(blank=True, help_text='Fresh vegetables close-up background', null=True, upload_to='sectors/cta/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
