# Generated by Django 5.0 on 2026-02-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tagline', models.CharField(help_text='Short catchy phrase', max_length=200)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='sectors/')),
                ('benefit_1_title', models.CharField(blank=True, max_length=100)),
                ('benefit_1_description', models.TextField(blank=True)),
                ('benefit_2_title', models.CharField(blank=True, max_length=100)),
                ('benefit_2_description', models.TextField(blank=True)),
                ('benefit_3_title', models.CharField(blank=True, max_length=100)),
                ('benefit_3_description', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Get in touch to discuss your requirements', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
