# Generated by Django 5.0 on 2026-03-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['slug'], name='sectors_sec_slug_0b7b3a_idx'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['is_active', 'order'], name='sectors_sec_is_acti_b1d356_idx'),
        ),
    ]
