# Generated by Django 5.0 on 2026-02-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='split_image',
            field=models.ImageField(blank=True, null=True, upload_to='sectors/'),
        ),
        migrations.AddField(
            model_name='sector',
            name='split_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='split_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sector',
            name='testimonial_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sector',
            name='testimonial_quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='testimonial_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sector',
            name='cta_text',
            field=models.CharField(default='Contact Our Team Today, Reach out to our helpful team today with any questions you may have to discuss your fruit and vegetable supply needs.We are more than happy to assist with any questions you may have. Source only the best in high-quality vegetables for your customers today!', max_length=200),
        ),
    ]
