# Generated by Django 5.0 on 2026-02-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_sector_split_image_sector_split_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='split_image',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='split_text',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='split_title',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='testimonial_author',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='testimonial_quote',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='testimonial_role',
        ),
    ]
