# Generated by Django 5.0 on 2026-02-23 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_remove_sector_split_image_remove_sector_split_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorFeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_sections', to='sectors.sector')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
