# Generated by Django 5.0 on 2026-03-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Terra Foods', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (recommended: 200x60px PNG)', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (32x32px)', null=True, upload_to='site/')),
                ('phone', models.CharField(default='+233 XXX XXX XXX', max_length=20)),
                ('email', models.EmailField(default='info@terrafoods.com', max_length=254)),
                ('whatsapp', models.CharField(default='233XXXXXXXXX', help_text='Without + sign', max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
