# Generated by Django 5.0 on 2026-03-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_created_at_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_page_description',
            field=models.TextField(blank=True, help_text='Detailed description shown on product list page when category is selected'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown on homepage/cards'),
        ),
    ]
